This notebook conatins python numpy examples.

In [1]:
# Let's import numpy

import numpy as np

In [2]:
x = np.array([3,6,8,3,2])

In [3]:
type(x)

numpy.ndarray

In [4]:
x.size

5

In [5]:
x

array([3, 6, 8, 3, 2])

In [6]:
x.ndim

1

In [7]:
x.shape

(5,)

In [8]:
x[1,]

6

In [9]:
x[:4]

array([3, 6, 8, 3])

In [10]:
np.save('x', x)

In [12]:
np.load('x.npy')

array([3, 6, 8, 3, 2])